[package]
name = "whatsapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gql_client = "1.0"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0.107"
polars = "0.33.2"